"""add is_shared to transactions

Revision ID: 268124a9d9c3
Revises: 4569675ea483
Create Date: 2026-08-28 23:58:04.616672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268124a9d9c3'
down_revision: Union[str, Sequence[str], None] = '4569675ea483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default: sem isto, adicionar uma coluna NOT NULL falha contra as
    # linhas já existentes (não sabem que valor pôr). O default fica no
    # schema — não é preciso removê-lo depois, `Transaction.is_shared` já
    # define o mesmo valor por omissão do lado do ORM.
    op.add_column(
        'transactions',
        sa.Column('is_shared', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_shared')
    # ### end Alembic commands ###
